-- SISTEMA SAEPSAÚDE — ESTRUTURA E IMPORTAÇÃO DOS CSVs
-- Execução recomendada: psql -d nome_do_banco -f Sistema_SAEPSaude_importacao.sql
-- Os arquivos usuarios.csv e Arquivoatividades.csv devem estar no diretório atual do psql.
-- Para outro diretório, altere os caminhos nas duas instruções \copy.

BEGIN;

DROP TABLE IF EXISTS comentarios CASCADE;
DROP TABLE IF EXISTS curtidas CASCADE;
DROP TABLE IF EXISTS atividades CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE usuarios (
    id_usuario INTEGER PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL DEFAULT 'senha_temporaria_alterar',
    tipo_usuario VARCHAR(20) NOT NULL
        CHECK (tipo_usuario IN ('funcionario', 'cliente')),
    data_cadastro TIMESTAMP NOT NULL
);

CREATE TABLE atividades (
    id_atividade INTEGER PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    tipo VARCHAR(100) NOT NULL,
    descricao TEXT,
    data_atividade DATE NOT NULL,
    duracao INTEGER NOT NULL CHECK (duracao >= 0),
    distancia NUMERIC(10, 2) NOT NULL CHECK (distancia >= 0),
    CONSTRAINT fk_atividades_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE curtidas (
    id_curtida INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_atividade INTEGER NOT NULL,
    data_curtida TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_curtida_usuario_atividade UNIQUE (id_usuario, id_atividade),
    CONSTRAINT fk_curtidas_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_curtidas_atividade FOREIGN KEY (id_atividade)
        REFERENCES atividades (id_atividade) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE comentarios (
    id_comentario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_atividade INTEGER NOT NULL,
    texto TEXT NOT NULL,
    data_comentario TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comentarios_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_comentarios_atividade FOREIGN KEY (id_atividade)
        REFERENCES atividades (id_atividade) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Tabelas temporárias com o formato original dos arquivos.
CREATE TEMP TABLE import_usuarios (
    id INTEGER,
    nome VARCHAR(100),
    email VARCHAR(150),
    tipo_usuario VARCHAR(20),
    data_cadastro DATE
) ON COMMIT DROP;

CREATE TEMP TABLE import_atividades (
    id INTEGER,
    usuario_id INTEGER,
    tipo_atividade VARCHAR(100),
    distancia_km NUMERIC(10, 2),
    duracao_min INTEGER,
    data_atividade DATE,
    descricao TEXT
) ON COMMIT DROP;

-- Importação real dos arquivos CSV; não há registros de usuários ou atividades escritos manualmente.
\copy import_usuarios (id, nome, email, tipo_usuario, data_cadastro) FROM 'usuarios.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');
\copy import_atividades (id, usuario_id, tipo_atividade, distancia_km, duracao_min, data_atividade, descricao) FROM 'Arquivoatividades.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

-- Validações antes da carga definitiva.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM import_usuarios GROUP BY id HAVING COUNT(*) > 1) THEN
        RAISE EXCEPTION 'usuarios.csv possui IDs duplicados';
    END IF;
    IF EXISTS (SELECT 1 FROM import_usuarios GROUP BY email HAVING COUNT(*) > 1) THEN
        RAISE EXCEPTION 'usuarios.csv possui e-mails duplicados';
    END IF;
    IF EXISTS (
        SELECT 1 FROM import_atividades a
        LEFT JOIN import_usuarios u ON u.id = a.usuario_id
        WHERE u.id IS NULL
    ) THEN
        RAISE EXCEPTION 'Arquivoatividades.csv possui usuario_id sem usuário correspondente';
    END IF;
END $$;

INSERT INTO usuarios (id_usuario, nome, email, tipo_usuario, data_cadastro)
SELECT id, nome, email, tipo_usuario, data_cadastro::timestamp
FROM import_usuarios
ORDER BY id;

INSERT INTO atividades (
    id_atividade, id_usuario, tipo, distancia, duracao, data_atividade, descricao
)
SELECT id, usuario_id, tipo_atividade, distancia_km, duracao_min,
       data_atividade, descricao
FROM import_atividades
ORDER BY id;

-- Garante que os próximos IDs automáticos não colidam com os dados importados.
SELECT setval(
    pg_get_serial_sequence('curtidas', 'id_curtida'),
    COALESCE((SELECT MAX(id_curtida) FROM curtidas), 1),
    false
);
SELECT setval(
    pg_get_serial_sequence('comentarios', 'id_comentario'),
    COALESCE((SELECT MAX(id_comentario) FROM comentarios), 1),
    false
);

COMMIT;

-- Conferência da importação.
SELECT COUNT(*) AS total_usuarios FROM usuarios;
SELECT tipo_usuario, COUNT(*) AS quantidade
FROM usuarios
GROUP BY tipo_usuario
ORDER BY tipo_usuario;
SELECT COUNT(*) AS total_atividades FROM atividades;
SELECT a.id_atividade, u.nome AS usuario, a.tipo, a.distancia,
       a.duracao, a.data_atividade, a.descricao
FROM atividades a
JOIN usuarios u ON u.id_usuario = a.id_usuario
ORDER BY a.id_atividade;
